# Generated by Django 5.2 on 2026-06-23 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeetCodeUserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('real_name', models.CharField(blank=True, max_length=100)),
                ('ranking', models.IntegerField()),
                ('reputation', models.IntegerField(default=0)),
                ('total_solved', models.IntegerField()),
                ('easy_solved', models.IntegerField()),
                ('medium_solved', models.IntegerField()),
                ('hard_solved', models.IntegerField()),
                ('contest_rating', models.FloatField(blank=True, null=True)),
                ('contest_global_ranking', models.IntegerField(blank=True, null=True)),
                ('attended_contests', models.IntegerField(default=0)),
                ('top_percentage', models.FloatField(blank=True, null=True)),
                ('avatar_url', models.URLField(blank=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
