# Generated by Django 5.2 on 2026-06-23 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leetcode', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leetcodeuseraccount',
            name='attended_contests',
        ),
        migrations.RemoveField(
            model_name='leetcodeuseraccount',
            name='contest_global_ranking',
        ),
        migrations.RemoveField(
            model_name='leetcodeuseraccount',
            name='contest_rating',
        ),
        migrations.RemoveField(
            model_name='leetcodeuseraccount',
            name='country',
        ),
        migrations.RemoveField(
            model_name='leetcodeuseraccount',
            name='top_percentage',
        ),
    ]
