# Generated by Django 5.2 on 2026-06-23 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leetcode', '0002_remove_leetcodeuseraccount_attended_contests_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leetcodeuseraccount',
            old_name='avatar_url',
            new_name='avatar',
        ),
        migrations.RenameField(
            model_name='leetcodeuseraccount',
            old_name='easy_solved',
            new_name='easy',
        ),
        migrations.RenameField(
            model_name='leetcodeuseraccount',
            old_name='hard_solved',
            new_name='hard',
        ),
        migrations.RenameField(
            model_name='leetcodeuseraccount',
            old_name='medium_solved',
            new_name='medium',
        ),
        migrations.RenameField(
            model_name='leetcodeuseraccount',
            old_name='total_solved',
            new_name='total',
        ),
    ]
