# Generated by Django 5.2 on 2026-06-29 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leetcode', '0003_rename_avatar_url_leetcodeuseraccount_avatar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeetCodeUserContestStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_rating', models.FloatField(blank=True, null=True)),
                ('contest_global_ranking', models.IntegerField(blank=True, null=True)),
                ('attended_contests', models.IntegerField(default=0)),
                ('top_percentage', models.FloatField(blank=True, null=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contest_stats', to='leetcode.leetcodeuseraccount')),
            ],
        ),
    ]
