# Generated by Django 5.2 on 2026-06-29 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leetcode', '0004_leetcodeuserconteststats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leetcodeuserconteststats',
            old_name='contest_global_ranking',
            new_name='global_ranking',
        ),
        migrations.AddField(
            model_name='leetcodeuserconteststats',
            name='total_participants',
            field=models.IntegerField(default=0),
        ),
    ]
