# Generated by Django 5.2 on 2026-07-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leetcode', '0005_rename_contest_global_ranking_leetcodeuserconteststats_global_ranking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leetcodeuseraccount',
            name='real_name',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
