# Generated by Django 5.2 on 2026-07-05 11:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leetcode', '0007_alter_leetcodeuseraccount_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leetcodeuserconteststats',
            name='contest_rating',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='leetcodeuserconteststats',
            name='global_ranking',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='leetcodeuserconteststats',
            name='top_percentage',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name='DailyStatsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('ranking', models.IntegerField()),
                ('reputation', models.IntegerField()),
                ('total', models.IntegerField()),
                ('easy', models.IntegerField()),
                ('medium', models.IntegerField()),
                ('hard', models.IntegerField()),
                ('contest_rating', models.FloatField(blank=True, null=True)),
                ('global_ranking', models.IntegerField(blank=True, null=True)),
                ('attended_contests', models.IntegerField(default=0)),
                ('total_participants', models.IntegerField(default=0)),
                ('top_percentage', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_snapshots', to='leetcode.leetcodeuseraccount')),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('account', 'date'), name='unique_daily_snapshot')],
            },
        ),
    ]
