# Generated by Django 5.2 on 2026-07-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leetcode', '0008_alter_leetcodeuserconteststats_contest_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leetcodeuserconteststats',
            name='attended_contests',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='leetcodeuserconteststats',
            name='total_participants',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
