# Generated by Django 5.2 on 2026-07-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leetcode', '0009_alter_leetcodeuserconteststats_attended_contests_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailystatssnapshot',
            name='attended_contests',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='dailystatssnapshot',
            name='total_participants',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
