# Generated by Django 5.2 on 2026-07-23 17:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leetcode', '0010_alter_dailystatssnapshot_attended_contests_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySkillStatsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('level', models.CharField(choices=[('fundamental', 'Fundamental'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('tag_name', models.CharField(max_length=100)),
                ('tag_slug', models.CharField(max_length=100)),
                ('problems_solved', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_skill_snapshots', to='leetcode.leetcodeuseraccount')),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('account', 'date', 'tag_slug', 'level'), name='unique_daily_skill_snapshot')],
            },
        ),
        migrations.CreateModel(
            name='LeetCodeUserSkillStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('fundamental', 'Fundamental'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('tag_name', models.CharField(max_length=100)),
                ('tag_slug', models.CharField(max_length=100)),
                ('problems_solved', models.IntegerField(default=0)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_stats', to='leetcode.leetcodeuseraccount')),
            ],
            options={
                'ordering': ['level', '-problems_solved'],
                'constraints': [models.UniqueConstraint(fields=('account', 'tag_slug', 'level'), name='unique_account_tag_level')],
            },
        ),
    ]
